#!/bin/bash
RGBSwitches="-b 1 -b 2 -b 3"
CIRSwitches="-b 4 -b 2 -b 1"
RGBMosaic1="-of vrt -cutline"
RGBMosaic2="-crop_to_cutline -dstalpha -multi"
CIRMosaic1="-of vrt -cutline"
CIRMosaic2="-crop_to_cutline -dstalpha -multi"
ExtraNDVI1="-of vrt -expand rgb"
NDVICut1="-of vrt -cutline"
NDVICut2="-crop_to_cutline -dstalpha -multi"
RGBTile1="-r bilinear -f hybrid"
RGBProj1="EPSG:$projection"
maxz="19"

pause(){
        read -p "Hit [ENTER] to go back to the previous menu.  I'll wait here..."
}

pause2() {
	read -p "Hit [ENTER] to start tiling, or Q to Exit...."
}

pause3() {
	read -p "Hit [ENTER] to manage mosaic cutting commands...."
}

get-max-z() {
clear
echo "What is the maximum zoom level you would like to tile?"
echo ""
echo "Explanation of Zoom Levels Here"
echo ""
echo -n "Please enter the maximum zoom level> "
read maxz
echo -e ""
read -p "Use maximum zoom level $maxz ?"
 if [[  ! $REPLY =~ ^[Yy]$ ]]; then
	printf "\nRestarting....\n"
	sleep 1
	get-max-z;
	else
	printf "\nContinuing...\n"
	sleep 1
	tile-rgb-then-cir-then-ndvi;
fi
}


get-project-projection() {
clear
echo -e "Please provide the projection for $SITENAME, using only the NUMBERS"
echo -e ""
echo -e "Example: 3417"
echo -e ""
echo -n "Enter the projection here> "
read projection
echo -e ""
read -p "Use projection EPSG:"$projection" ?"
 if [[  ! $REPLY =~ ^[Yy]$ ]]; then
	printf "\nRestarting....\n"
	sleep 1
	get-project-projection;
	else
	printf "\nContinuing...\n"
	sleep 1
	get-max-z;
fi
}

tile-rgb-then-cir-then-ndvi() {
clear
echo -e "In this step, the script will put jobs into SCREEN mode.  You will need to"
echo -e "understand how to operate SCREEN in order to monitor jobs."
echo -e ""
echo -e "Disconnect from a screen    :  Press and hold CTRL and press A then D"
echo -e "Move to the next screen     :"
echo -e "See a menu of active screens:"
echo -e ""
echo -e ""
screen -dmS "$SITENAME"_RGB bash -c "cd /var/www/mapproxy; sudo python /usr/local/bin/mapslicer.py -r bilinear -f hybrid -s EPSG:$projection -z 0-$maxz data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$rgbtilepath"/rgbtemp.vrt tiles/$client/"$SITENAME"_rgb"
screen -dmS "$SITENAME"_CIR bash -c "cd /var/www/mapproxy; sudo python /usr/local/bin/mapslicer.py -r bilinear -f hybrid -s EPSG:$projection -z 0-$maxz data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$rgbtilepath"/cirtemp.vrt tiles/$client/"$SITENAME"_cir"
screen -dmS "$SITENAME"_NDVI bash -c "cd /var/www/mapproxy; sudo python /usr/local/bin/mapslicer.py -r bilinear -f hybrid -s EPSG:$projection -z 0-$maxz data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$rgbtilepath"/gndvitemp.vrt tiles/$client/"$SITENAME"_gndvi"
}

#edit-ndvi-tiling() {
#tile-rgb-then-cir-then-ndvi;
#}

#edit-cir-tiling() {
#	edit-ndvi-tiling;
#}

edit-rgb-tiling() {
clear
echo -s "You may edit the tiling options now" 
	edit-cir-tiling;
}

cut-data-to-shapefiles() {
clear
cd /var/www/mapproxy
pwd
echo -e "In this step, we will cut all RGB, CIR and NDVI data to the shapefile."
echo -e ""
echo -e "All of the options should have been edited in the previous steps."
echo -e ""
echo -e "Cutting RGB Data to shapefile using command: "
echo -e "sudo gdalwarp $RGBMosaic1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $RGBMosaic2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/rgb.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/rgbtemp.vrt"
echo -e ""
cd /var/www/mapproxy
sudo gdalwarp $RGBMosaic1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $RGBMosaic2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/rgb.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/rgbtemp.vrt
echo -e "Cutting CIR Data to shapefile using command: "
echo -e "sudo gdalwarp $CIRMosaic1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $CIRMosaic2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/cir.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/cirtemp.vrt"
echo -e ""
cd /var/www/mapproxy
sudo gdalwarp $CIRMosaic1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $CIRMosaic2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/cir.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/cirtemp.vrt
echo -e "Cutting NDVI Data to shapefile using command: "
echo -e "sudo gdalwarp $NDVICut1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $NDVICut2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/gndvitr.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/gndvitemp.vrt"
echo -e ""
cd /var/www/mapproxy
sudo gdalwarp $NDVICut1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $NDVICut2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/gndvitr.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/gndvitemp.vrt
edit-rgb-tiling;
}


ndvi-mosaic-edit() {
clear
echo -e "In this step, you will edit the NDVI shapefile cutting command, if necessary."
echo -e ""
echo -e "Current NDVI Shapefile Cut Command:"
echo -e "sudo gdalwarp $NDVICut1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $NDVICut2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/rgb.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/rgbtemp.vrt"
echo -e ""
echo -e "1) Change $NDVICut1"
echo -e "2) Change $NDVICut2"
echo -e "3) Cut Data to Shapefiles"
echo -e ""
echo -n "Enter your selection here> "
ndvieditmenu;
}

ndvieditmenu() {
read selection
case $selection in
        1) echo "Changing first mosaic switches....";
                read -p "What would you like to change the first mosaic switches to? "
                NDVICut1=$REPLY;
                ndvi-mosaic-edit;
                ;;
        2) echo "Changing second mosaic switches....";
                read -p "What would you like to change the second mosaic switches to? "
                NDVICut2=$REPLY;
                ndvi-mosaic-edit;
                ;;
        3) echo "Moving on to cut data to shapefiles..."
                cut-data-to-shapefiles;
                ;;
        *) echo -e "Where are your manners?  Choose a correct entry.  $REPLY is not a valid choice."
                ndvieditmenu;
                ;;
esac
}



cir-mosaic-edit() {
clear
echo -e "In this step, you will edit the CIR shapefile cutting command, if necessary."
echo -e ""
echo -e "Current CIR Shapefile Cut Command:"
echo -e "sudo gdalwarp $CIRMosaic1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $CIRMosaic2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/rgb.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/rgbtemp.vrt"
echo -e ""
echo -e "1) Change $CIRMosaic1"
echo -e "2) Change $CIRMosaic2"
echo -e "3) Move on to NDVI Edit Menu"
echo -e ""
echo -n "Enter your selection here> "
cireditmenu;
}

cireditmenu() {
read selection
case $selection in
        1) echo "Changing first mosaic switches....";
                read -p "What would you like to change the first mosaic switches to? "
                CIRMosaic1=$REPLY;
                cir-mosaic-edit;
                ;;
        2) echo "Changing second mosaic switches....";
                read -p "What would you like to change the second mosaic switches to? "
                CIRMosaic2=$REPLY;
                cir-mosaic-edit;
                ;;
        3) echo "Moving on to NDVI Edit Menu..."
                ndvi-mosaic-edit;
                ;;
        *) echo -e "Where are your manners?  Choose a correct entry.  $REPLY is not a valid choice."
                cireditmenu;
                ;;
esac
}


rgb-mosaic-edit() {
clear
echo -e "In this step, you will edit the RGB shapefile cutting command, if necessary."
echo -e ""
echo -e "Current RGB Shapefile Cut Command:"
echo -e "sudo gdalwarp $RGBMosaic1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename $RGBMosaic2 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/rgb.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/rgbtemp.vrt"
echo -e ""
echo -e "1) Change $RGBMosaic1"
echo -e "2) Change $RGBMosaic2"
echo -e "3) Move on to CIR Edit Menu"
echo -e ""
echo -n "Enter your selection here> "
rgbeditmenu;
}

rgbeditmenu() {
read selection
case $selection in
        1) echo "Changing first mosaic switches....";
                read -p "What would you like to change the first mosaic switches to? "
                RGBMosaic1=$REPLY;
                rgb-mosaic-edit;
                ;;
        2) echo "Changing second mosaic switches....";
                read -p "What would you like to change the second mosaic switches to? "
                RGBMosaic2=$REPLY;
                rgb-mosaic-edit;
                ;;
	3) echo "Moving on to CIR Edit Menu..."
		cir-mosaic-edit;
		;;
	*) echo -e "Where are your manners?  Choose a correct entry.  $REPLY is not a valid choice."
		rgbeditmenu;
		;;
esac
}

create-rgb-cir-mosaic() {
clear
echo -e "I will now create the mosaics for the RGB, CIR and NDVI imagery."
echo -e ""
echo -e "Then you will be able to edit the options for croppingt to the shapefile.  Please stand by...."
echo -e ""
cd /var/www/mapproxy
echo -e "Creating RGB Mosaic using command:"
echo -e "sudo gdalbuildvrt $RGBSwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$rgbtilepath"/rgb.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$rgbtilepath"/*."$inputfiletype""
echo -e ""
sudo gdalbuildvrt $RGBSwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$rgbtilepath"/rgb.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$rgbtilepath"/*."$inputfiletype"
echo -e ""
echo -e ""
echo -e "Creating CIR Mosaic using command:"
echo -e "sudo gdalbuildvrt $CIRSwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$cirtilepath"/cir.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$cirtilepath"/*."$inputfiletype""
echo -e ""
sudo gdalbuildvrt $CIRSwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$cirtilepath"/cir.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$cirtilepath"/*."$inputfiletype"
echo -e " "
echo -e " "
echo -e "Creating NDVI Mosaic using command:"
echo -e "sudo gdalbuildvrt $NDVISwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$SITENAME"/gndvi.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$ndvitilepath"/*."$inputfiletype""
echo -e ""
sudo gdalbuildvrt $NDVISwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$SITENAME"/gndvi.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$ndvitilepath"/*."$inputfiletype"
echo ""
echo ""
echo -e "Doing the extra NDVI Step using command:"
echo -e "sudo gdal_translate $ExtraNDVI1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$SITENAME"/gndvi.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$SITENAME"/gndvitr.vrt"
echo -e ""
sudo gdal_translate $ExtraNDVI1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$SITENAME"/gndvi.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$SITENAME"/gndvitr.vrt
echo ""
echo ""
pause3;
rgb-mosaic-edit;
}

get-shape-file() {
clear
echo -e "\e[92mPlease enter the name of the shape file.  CAPITALIZATION COUNTS!"
echo ""
echo "Hint: /var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp"
echo "is the assumed SHP file directory based on previous answers."
echo ""
echo -e "If you do not know the name, press Q to quit until you have the name."
echo ""
read shapefilename
if [ "$shapefilename" == "Q" ]; then
        echo "Exiting this module... chicken."
        sleep 1
        pause
        exit
elif [ "$shapefilename" == "q" ]; then
        echo "Exiting this module... chicken."
        sleep 1
        pause
        exit
else
	if [ -e "/var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/shp/$shapefilename" ]; then
	rgbaction;
else
	echo "The shapefile you entered does not exist on the path.  Please try again."
	sleep 3
	get-shape-file;
fi
fi
}

check-ndvi-path() {
clear
echo "NDVI Input Tile Path"
echo ""
echo ""
echo "Hint: /var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/ is assumed"
echo "because of your previous entries."
echo ""
echo "Example:  AgPerformance"
echo ""
echo ""
echo -e "\e[92mPlease enter the path to the NDVI \e[92mimages you wish to tile: \e[0m"
read ndvitilepath
if [ "$ndvitilepath" == "Q" ]; then
	echo "Exiting this module... chicken."
	sleep 1
	pause;
	exit
elif [ "$ndvitilepath" == "q" ]; then
	echo "Exiting this module... chicken."
	sleep 1
	pause;
	exit
else
test -n "$(find /var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$ndvitilepath" -maxdepth 1 -name "*.$inputfiletype" -print -quit)"
        if [ "$?" == "0" ]; then
        get-shape-file;
else
	echo "No files of type $inputfiletype exist at the path.  Make sure you are using lowercase, and try again."
	check-ndvi-path;
fi
fi
}


check-cir-path() {
clear
echo "CIR Input Tile Path"
echo ""
echo ""
echo "Hint: /var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/ is assumed"
echo "because of your previous entries."
echo ""
echo "Example:  AgPerformance"
echo ""
echo ""
echo -e "\e[92mPlease enter the path to the CIR \e[92mimages you wish to tile: \e[0m"
read cirtilepath
if [ "$cirtilepath" == "Q" ]; then
	echo "Exiting this module... chicken."
	sleep 1
	pause;
	exit
elif [ "$cirtilepath" == "q" ]; then
	echo "Exiting this module... chicken."
	sleep 1
	pause;
	exit
else
test -n "$(find /var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$cirtilepath" -maxdepth 1 -name "*.$inputfiletype" -print -quit)"
        if [ "$?" == "0" ]; then
        check-ndvi-path;
else
	echo "No files of type $inputfiletype exist at the path.  Make sure you are using lowercase, and try again."
	check-cir-path;
fi
fi
}


printndvimenu() {
echo -e	"1) Change the project year"
echo -e "2) Change the project season"
echo -e "3) Change the input file type"
echo -e "4) Change the client name"
echo -e "5) Change the Site Name"
echo -e "6) Change the command switches"
echo -e "7) Add ADDITIONAL command switches"
echo ""
echo -e "0) Continue with this command line"
echo -e "Q) Quit This Module"
echo ""
echo -n "Make your selection here. > "
ndvimenu;
}



ndvimenu() {
read selection
case $selection in
        1) echo "Changing Project Year....";
                read -p "What would you like to change the project year to? " -n 2 -r;
                PROJECTYEAR=$REPLY;
                ndviaction;
                ;;
        2) echo "Changing Project Season....";
                read -p "What would you like to change the project season to? " -n 2 -r;
                PROJECTSEASON=$REPLY;
                ndviaction;
                ;;
        3) echo "Changing Project Input File Type....";
                read -p "What would you like to change the input filetype to? " -r;
                inputfiletype=$REPLY;
                ndviaction;
                ;;
        4) echo "Changing Client Name....";
                read -p "What would you like to change the client name to? " -r;
                client=$REPLY;
                ndviaction;
                ;;
        5) echo "Changing Site Name....";
                read -p "What would you like to change the site name to? " -r;
                SITENAME=$REPLY;
                ndviaction;
                ;;
        6) echo "Changing Command Switches....";
                read -p "What would you like to change the command switches to? " -r;
                NDVISwitches=$REPLY;
                ndviaction;
                ;;
        7) echo "Adding ADDITIONAL Command Switches....";
                read -p "What other command switches would you like to add? " -r;
                NDVISwitches=$NDVISwitches" $REPLY";
                ndviaction;
                ;;
        0) echo "Continuing to NDVI Extra Action Editing Menu....";
                ndviExtraAction;
                ;;
        Q) echo "Exiting this module....";
                sleep 1;
                exit;
                ;;
        *) echo "Please make a valid choice....";
                sleep 1;
                ndviaction;
                ;;
        esac
}

ndviExtraAction() {
clear
echo "Getting ready to put your entries into action.  Please review the options, and press"
echo "the corresponding button in order to make a change."
echo ""
echo "NDVI EXTRA STEP Mosaic Command:"
echo ""
echo "sudo gdal_translate $ExtraNDVI1 data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/gndvi.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/*.$inputfiletype"
echo ""
echo "Press a menu option below to change the command line."
echo ""
printndviExtramenu;
}

printndviExtramenu() {
echo -e	"1) Change the project year"
echo -e "2) Change the project season"
echo -e "3) Change the input file type"
echo -e "4) Change the client name"
echo -e "5) Change the Site Name"
echo -e "6) Change Command Switches"
echo -e "7) Add ADDITIONAL command switches"
echo ""
echo -e "0) Continue with this command line"
echo -e "Q) Quit This Module"
echo ""
echo -n "Make your selection here. > "
ndviExtramenu;
}



ndviExtramenu() {
read selection
case $selection in
        1) echo "Changing Project Year....";
                read -p "What would you like to change the project year to? " -n 2 -r;
                PROJECTYEAR=$REPLY;
                ndviExtraAction;
                ;;
        2) echo "Changing Project Season....";
                read -p "What would you like to change the project season to? " -n 2 -r;
                PROJECTSEASON=$REPLY;
                ndviExtraAction;
                ;;
        3) echo "Changing Project Input File Type....";
                read -p "What would you like to change the input filetype to? " -r;
                inputfiletype=$REPLY;
                ndviExtraAction;
                ;;
        4) echo "Changing Client Name....";
                read -p "What would you like to change the client name to? " -r;
                client=$REPLY;
                ndviExtraAction;
                ;;
        5) echo "Changing Site Name....";
                read -p "What would you like to change the site name to? " -r;
                SITENAME=$REPLY;
                ndviExtraAction;
                ;;
        6) echo "Changing Command Switches....";
                read -p "What would you like to change the command switches to? " -r;
                ExtraNDVI1=$REPLY;
                ndviExtraAction;
                ;;
        7) echo "Adding ADDITIONAL Command Switches....";
                read -p "What other command switches would you like to add? " -r;
                ExtraNDVI1=$ExtraNDVI1" $REPLY";
                ndviExtraAction;
                ;;
        0) echo "Continuing to Tile Command Editing Menu....";
                create-rgb-cir-mosaic;
                ;;
        Q) echo "Exiting this module....";
                sleep 1;
                exit;
                ;;
        *) echo "Please make a valid choice....";
                sleep 1;
                ndviExtraAction;
                ;;
        esac
}

ndviaction() {
clear
echo "Getting ready to put your entries into action.  Please review the options, and press"
echo "the corresponding button in order to make a change."
echo ""
echo "NDVI Mosaic Command:"
echo ""
echo "sudo gdalbuildvrt $NDVISwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/gndvi.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/*.$inputfiletype"
echo ""
echo "Press a menu option below to change the command line."
echo ""
printndvimenu;
}




printcirmenu() {
echo -e "1) Change the project year"
echo -e "2) Change the project season"
echo -e "3) Change the input file type"
echo -e "4) Change the client name"
echo -e "5) Change the Site Name"
echo -e "6) Change the command switches"
echo -e "7) Add ADDITIONAL command switches"
echo ""
echo -e "0) Continue with this command line"
echo -e "Q) Quit"
echo ""
echo -n "Make your selection here. > "
cirmenu;
}



cirmenu() {
read selection
case $selection in
        1) echo "Changing Project Year....";
                read -p "What would you like to change the project year to? " -n 2 -r;
                PROJECTYEAR=$REPLY;
                ciraction;
                ;;
        2) echo "Changing Project Season....";
                read -p "What would you like to change the project season to? " -n 2 -r;
                PROJECTSEASON=$REPLY;
                ciraction;
                ;;
        3) echo "Changing Project Input File Type....";
                read -p "What would you like to change the input filetype to? " -r;
                inputfiletype=$REPLY;
                ciraction;
                ;;
        4) echo "Changing Client Name....";
                read -p "What would you like to change the client name to? " -r;
                client=$REPLY;
                ciraction;
                ;;
        5) echo "Changing Site Name....";
                read -p "What would you like to change the site name to? " -r;
                SITENAME=$REPLY;
                ciraction;
                ;;
        6) echo "Changing Command Switches....";
                read -p "What would you like to change the command switches to? " -r;
                CIRSwitches=$REPLY;
                ciraction;
                ;;
        7) echo "Adding ADDITIONAL Command Switches....";
                read -p "What other command switches would you like to add? " -r;
                CIRSwitches=$CIRSwitches" $REPLY";
                ciraction;
                ;;
        0) echo "Continuing to NDVI Command Display....";
		ndviaction;
                ;;
	Q) echo "Exiting this module....";
		sleep 1;
		exit;
		;;
	*) echo "Please make a valid choice....";
		sleep 1;
		ciraction;
		;;
        esac
}

ciraction() {
clear
echo "Getting ready to put your entries into action.  Please review the options, and press"
echo "the corresponding button in order to make a change."
echo ""
echo "CIR Mosaic Command:"
echo ""
echo "sudo gdalbuildvrt $CIRSwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/cir.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/*.$inputfiletype"
echo ""
echo "Press a menu option below to change the command line."
echo ""
printcirmenu;
}





printrgbmenu() {
echo -e "1) Change the project year"
echo -e "2) Change the project season"
echo -e "3) Change the input file type"
echo -e "4) Change the client name"
echo -e "5) Change the Site Name"
echo -e "6) Change the command switches"
echo -e "7) Add ADDITIONAL command switches"
echo ""
echo -e "0) Continue with this command line"
echo -e "Q) Quit This Module"
echo ""
echo -n "Make your selection here. > "
rgbmenu;
}



rgbmenu() {
read selection
case $selection in
	1) echo "Changing Project Year....";
		read -p "What would you like to change the project year to? " -n 2 -r;
		PROJECTYEAR=$REPLY;
		rgbaction;
		;;
	2) echo "Changing Project Season....";
		read -p "What would you like to change the project season to? " -n 2 -r;
		PROJECTSEASON=$REPLY;
		rgbaction;
		;;
	3) echo "Changing Project Input File Type....";
		read -p "What would you like to change the input filetype to? " -r;
		inputfiletype=$REPLY;
		rgbaction;
		;;
	4) echo "Changing Client Name....";
		read -p "What would you like to change the client name to? " -r;
		client=$REPLY;
		rgbaction;
		;;
	5) echo "Changing Site Name....";
		read -p "What would you like to change the site name to? " -r;
		SITENAME=$REPLY;
		rgbaction;
		;;
	6) echo "Changing Command Switches....";
		read -p "What would you like to change the command switches to? " -r;
		RGBSwitches=$REPLY;
		rgbaction;
		;;
	7) echo "Adding ADDITIONAL Command Switches....";
		read -p "What other command switches would you like to add? " -r;
		RGBSwitches=$RGBSwitches" $REPLY";
		rgbaction;
		;;
	0) echo "Continuing to CIR Command Display....";
		ciraction;
		;;
	Q) echo "Exiting this module....";
		sleep 1;
		exit;
		;;
	*) echo "Please make a valid choice....";
		sleep 1;
		rgbaction;
		;;
	esac
}

rgbaction() {
clear
echo "Getting ready to put your entries into action.  Please review the options, and press"
echo "the corresponding button in order to make a change."
echo ""
echo "RGB Mosaic Command:"
echo ""
echo "sudo gdalbuildvrt $RGBSwitches data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/rgb.vrt data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME/*.$inputfiletype"
echo ""
echo "Press a menu option below to change the command line."
echo ""
printrgbmenu;
}


getrgbtilepath() {
clear
echo "RGB Input Tile Path"
echo ""
echo ""
echo "Hint: /var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/ is assumed"
echo "because of your previous entries."
echo ""
echo "Example:  AgPerformance"
echo ""
echo ""
echo -e "\e[92mPlease enter the path to the \e[91mR\e[92mG\e[36mB \e[92mimages you wish to tile: \e[0m"
read rgbtilepath
if [ "$rgbtilepath" == "Q" ]; then
	echo "Exiting this module... chicken."
	sleep 1
	pause;
	exit
elif [ "$rgbtilepath" == "q" ]; then
	echo "Exiting this module... chicken."
	sleep 1
	pause;
	exit
else
test -n "$(find /var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/"$rgbtilepath" -maxdepth 1 -name "*.$inputfiletype" -print -quit)"
	if [ "$?" == "0" ]; then
	check-cir-path;
else
	echo -e "There are not files of type: $inputfiletype  in the path that you specified."
	echo -e "Please make sure you are using lowercase letters, and try again."
	getrgbtilepath;
fi
fi
}

express-input-file-type() {
clear
echo "Input File Type"
echo ""
echo ""
echo "This module assumes you know the location of the data to be tiled.  Your"
echo "responses will be checked to make sure that the data is actually there.  You"
echo "should note, this script will NOT check to see if you have entered the CORRECT"
echo "data, it will only check to see that it is, in fact, being provided some."
echo ""
echo ""
echo "If you are uncertain that you have the correct path to the data to be tiled,"
echo "you should press Q immediately and check your path."
echo ""
echo ""
echo -e "\033[5mIf at ANY point you are unable to answer a question properly at a prompt,  the" 
echo -e "\033[5mbest policy is to select Q and exit to the main menu until you can answer all"
echo -e "\033[5mquestions. with 100% accuracy.\033[0m"
echo ""
echo ""
echo -e "\e[92mPlease tell me the input file type (tif, jpg, gif) USE LOWERCASE!\e[0m"
read inputfiletype
if [ "$inputfiletype" == "Q" ]; then
        echo "Exiting this module... chicken."
        sleep 1
        pause;
        exit
elif [ "$inputfiletype" == "q" ]; then
        echo "Exiting this module... chicken."
        sleep 1
        pause;
        exit
else
	getrgbtilepath;
fi
}

does-not-exist(){
echo "The file path, or the extension you selected, does not exist."
echo ""
sleep 1
pause
exit
}

get-site-name() {
echo "The SITE NAME attribute determines which dataset we should process for $client."
echo "You should already have an idea of the site name, as it is usually in the file"
echo "name for the original TIF / JPG file."
echo ""
read -p "Please enter a site name : "
SITENAME=$REPLY
printf "\nYou have chosen $SITENAME\n"
echo "We are now going to check that the entire directory exists....."
if [ -d "/var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/$SITENAME"/ ]; then
	echo "Directory exists... continuing..."
	express-input-file-type;
else
read -p "This directory does not exist... create? " -n 1 -r
 if [[  ! $REPLY =~ ^[Yy]$ ]]; then
        printf "\nExiting....\n"
 else
        sudo mkdir -p /var/www/mapproxy/data_$client/$PROJECTYEAR_season$PROJECTSEASON/$SITENAME
        express-input-file-type;
fi
fi
}

get-season() {
echo "Please input the repeat flight number."
echo "This is the number of times this particular data has been flown."
echo ""
echo "First flight will be flight 1, next flight will be flight 2, etc."
echo ""
echo "I will check to make sure that the client and repeat directories have been created."
echo ""
read -p "Please enter the NUMERIC repeat flight number> " -n 2 -r
PROJECTSEASON=$REPLY
printf "\nYou have chosen season: $PROJECTSEASON\n"
read -p "Would you like to continue with this season number?" -n 1 -r
 if [[  ! $REPLY =~ ^[Yy]$ ]];
                then
        printf "\nExiting....\n"
        pause;
        exit
        else
printf  "\nTesting to see if /var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON" exists\n"
if [ -d "/var/www/mapproxy/data_$client/"$PROJECTYEAR"_season"$PROJECTSEASON"/" ]; then
	echo "Directory exists... continuing..."
	get-site-name;
else
	read -p "Directory does not exist... create? " -n 1 -r
 if [[  ! $REPLY =~ ^[Yy]$ ]]; then
	printf "\nExiting....\n"
 else
	sudo mkdir -p /var/www/mapproxy/data_$client/$PROJECTYEAR_season$PROJECTSEASON/
	get-site-name;
fi
fi
fi
}

get-project-year() {
echo "Please input the project year.  Please enter all four digits of the year."
echo ""
echo "Example:  2015"
echo ""
read -p "Please enter the project year " -n 4 -r
PROJECTYEAR=$REPLY
printf "\nYou have specified project year $PROJECTYEAR"
echo ""
read -p "Would you like to continue with this year? " -n 1 -r
 if [[  ! $REPLY =~ ^[Yy]$ ]];
                then
        printf "\nExiting....\n"
        pause;
        exit
        else
        printf "\nContinuing with Project Year set to $PROJECTYEAR...\n"
	get-season;
fi
}

check-client-dir() {
if [ -d "/var/www/mapproxy/data_$client" ]; then
	echo ""
	echo "Directory /var/www/mapproxy/data_$client exists.  Moving on."
	get-project-year;
else
	read -p "Directory /var/www/mapproxy/data_$client does not exist.  Create it? " -n 1 -r
	if [[  ! $REPLY =~ ^[Yy]$ ]];
		then
	printf "\nExiting....\n"
	pause;
	exit
	else
	printf "\nCreating directory /var/www/mapproxy/data_$client...\n"
	sudo mkdir -p /var/www/mapproxy/data_$client
	get-project-year;
fi
fi
}


get-client() {
clear
echo "Specify the name of the client.  The client name will be appended to /var/www/mapproxy/data_client"
echo ""
echo "Example:  fn for Farm Nutrients will use or create the directory /var/www/mapproxy/data_fn"
echo ""
echo "If the directory already exists, it will be used.  If the directory does NOT exist, it will be created."
echo ""
echo -n "Please enter the client name (limit 8 alphabetic characters)"
read client 
if [ "$inputfiletype" == "Q" ]; then
        echo "Exiting this module... chicken."
        sleep 1
        pause;
        exit
elif [ "$inputfiletype" == "q" ]; then
        echo "Exiting this module... chicken."
        sleep 1
        pause;
        exit
else
	check-client-dir;
fi
}

get-client

